apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pulsar-argocd-evaluation
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: argocd-apps
    repoURL: 'https://github.com/Rajendra08/argocd-pulsar-desired'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
