apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pulsar-app-final
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: pulsar
    server: 'https://kubernetes.default.svc'
  source:
    path: my-apps/pulsar-cluster
    repoURL: 'https://github.com/Rajendra08/argocd-pulsar-desired'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    automated: {}
