apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pulsar-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2" 
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: sn-pf
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.streamnative.io'
    targetRevision: 0.8.23
    chart: pulsar-operator
  project: default
  syncPolicy:
    automated: {}
