apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pulsar-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: pulsar
    server: 'https://kubernetes.default.svc'
  source:
    path: pulsar-apps/sn-platform
    repoURL: 'https://github.com/Rajendra08/argocd-pulsar-desired'
    targetRevision: HEAD
    helm:
      parameters:
        - name: initialize
          value: "true"
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    automated: {}
